version: "3"

services:
  app1:
    build:
      context: ./app1
      dockerfile: Dockerfile.dev
    container_name: app1
    environment:
      MIX_ENV: dev
    stdin_open: true
    tty: true
    volumes:
      - ./app1:/app

  app2:
    build:
      context: ./app2
      dockerfile: Dockerfile.dev
    container_name: app2
    environment:
      MIX_ENV: dev
    stdin_open: true
    tty: true
    volumes:
      - ./app2:/app

  app3:
    build:
      context: ./app3
      dockerfile: Dockerfile.dev
    container_name: app3
    environment:
      MIX_ENV: dev
    stdin_open: true
    tty: true
    volumes:
      - ./app3:/app
